--- 
abstract: Conversion between Unicode Character Maps
author: Audrey Tang <cpan@audreyt.org>
distribution_type: module
generated_by: Module::Install version 0.67
license: mit
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Convert-CharMap
no_index: 
  directory: 
    - inc
    - t
provides: 
  Convert::CharMap: 
    file: lib/Convert/CharMap.pm
    version: 0.10
  Convert::CharMap::CharMapML: 
    file: lib/Convert/CharMap/CharMapML.pm
  Convert::CharMap::UCM: 
    file: lib/Convert/CharMap/UCM.pm
  Convert::CharMap::YAML: 
    file: lib/Convert/CharMap/YAML.pm
requires: 
  XML::Simple: 0
  charnames: 0
  perl: 5.6.0
version: 0.10
